Config = {}
Config.defaultTargetIcon = 'shopping-basket'
Config.defaultTargetLabel = 'Open Shop'

-- Deliveries
Config.ShopsInvJsonFile = 'shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'GO Postal', coords = Vector(69.0862, 127.6753, 79.2123) },
    ['vehicleWithdraw'] = Vector(71.9318, 120.8389, 79.0823),
    ['vehicleDeposit'] = Vector(62.7282, 124.9846, 79.0926),
    ['stores'] = {}, -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['normal'] = {
        { name = 'tosti', price = 2, amount = 50 },
        { name = 'water_bottle', price = 2, amount = 50 },
        { name = 'kurkakola', price = 2, amount = 50 },
        { name = 'twerks_candy', price = 2, amount = 50 },
        { name = 'snikkel_candy', price = 2, amount = 50 },
        { name = 'sandwich', price = 2, amount = 50 },
        { name = 'beer', price = 7, amount = 50 },
        { name = 'whiskey', price = 10, amount = 50 },
        { name = 'vodka', price = 12, amount = 50 },
        { name = 'bandage', price = 100, amount = 50 },
        { name = 'lighter', price = 2, amount = 50 },
        { name = 'rolling_paper', price = 2, amount = 5000 },
        { name = 'item_bench', price = 0, amount = 10 },
    },
    ['liquor'] = {
        { name = 'beer', price = 7, amount = 50 },
        { name = 'whiskey', price = 10, amount = 50 },
        { name = 'vodka', price = 12, amount = 50 },
    },
    ['hardware'] = {
        { name = 'lockpick', price = 200, amount = 50 },
        --{ name = 'weapon_wrench',     price = 250, amount = 250, },
        --{ name = 'weapon_hammer',     price = 250, amount = 250, },
        { name = 'repairkit', price = 250, amount = 50, requiredJob = { 'mechanic', 'police' } },
        { name = 'screwdriverset', price = 350, amount = 50 },
        { name = 'phone', price = 850, amount = 50 },
        { name = 'radio', price = 250, amount = 50 },
        { name = 'binoculars', price = 50, amount = 50 },
        { name = 'firework1', price = 50, amount = 50 },
        { name = 'firework2', price = 50, amount = 50 },
        { name = 'firework3', price = 50, amount = 50 },
        { name = 'firework4', price = 50, amount = 50 },
        { name = 'cleaningkit', price = 150, amount = 150 },
        { name = 'advancedrepairkit', price = 500, amount = 50, requiredJob = 'mechanic' },
    },
    ['weedshop'] = {
        { name = 'joint', price = 10, amount = 50 },
        { name = 'weed_nutrition', price = 20, amount = 50 },
        { name = 'empty_weed_bag', price = 2, amount = 1000 },
        { name = 'rolling_paper', price = 2, amount = 1000 },
    },
    ['gearshop'] = {
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'jerry_can', price = 200, amount = 50 },
    },
    ['leisureshop'] = {
        { name = 'parachute', price = 2500, amount = 10 },
        { name = 'binoculars', price = 50, amount = 50 },
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'diving_fill', price = 500, amount = 10 },
    },
    ['weapons'] = {
        { name = 'weapon_acm', price = 0, amount = 250 },
        { name = 'weapon_austro', price = 0, amount = 250 },
        { name = 'weapon_banshee', price = 0, amount = 250 },
        { name = 'weapon_bison', price = 0, amount = 250 },
        { name = 'weapon_cs446', price = 0, amount = 250 },
        { name = 'weapon_condor', price = 0, amount = 250 },
        { name = 'weapon_convert', price = 0, amount = 250 },
        { name = 'weapon_db12', price = 0, amount = 250 },
        { name = 'weapon_dnc68', price = 0, amount = 250 },
        { name = 'weapon_fang', price = 0, amount = 250 },
        { name = 'weapon_fierro', price = 0, amount = 250 },
        { name = 'weapon_finisher', price = 0, amount = 250 },
        { name = 'weapon_freq', price = 0, amount = 250 },
        { name = 'weapon_gaston', price = 0, amount = 250 },
        { name = 'weapon_kal', price = 0, amount = 250 },
        { name = 'weapon_kfs', price = 0, amount = 250 },
        { name = 'weapon_ktk', price = 0, amount = 250 },
        { name = 'weapon_krink', price = 0, amount = 250 },
        { name = 'weapon_lws32', price = 0, amount = 250 },
        { name = 'weapon_n77', price = 0, amount = 250 },
        { name = 'weapon_mk4', price = 0, amount = 250 },
        { name = 'weapon_mirage', price = 0, amount = 250 },
        { name = 'weapon_mouflan', price = 0, amount = 250 },
        { name = 'weapon_orion', price = 0, amount = 250 },
        { name = 'weapon_pn99', price = 0, amount = 250 },
        { name = 'weapon_ppy', price = 0, amount = 250 },
        { name = 'weapon_patriot', price = 0, amount = 250 },
        { name = 'weapon_pitviper', price = 0, amount = 250 },
        { name = 'weapon_queen80', price = 0, amount = 250 },
        { name = 'weapon_remi', price = 0, amount = 250 },
        { name = 'weapon_roger', price = 0, amount = 250 },
        { name = 'weapon_roma12', price = 0, amount = 250 },
        { name = 'weapon_ronin777', price = 0, amount = 250 },
        { name = 'weapon_sabra', price = 0, amount = 250 },
        { name = 'weapon_sovwhisper', price = 0, amount = 250 },
        { name = 'weapon_vulcan', price = 0, amount = 250 },
        { name = 'weapon_flashlight', price = 0, amount = 250 },
    },
    ['prison'] = {
        { name = 'sandwich', price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        -- { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        -- { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        -- { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        -- { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        -- { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' }, } } },
        -- { name = 'weapon_nightstick',   price = 0, amount = 50 },
        -- { name = 'weapon_flashlight',   price = 0, amount = 50 },
        { name = 'pistol_ammo', price = 0, amount = 50 },
        { name = 'smg_ammo', price = 0, amount = 50 },
        { name = 'shotgun_ammo', price = 0, amount = 50 },
        { name = 'rifle_ammo', price = 0, amount = 50 },
        { name = 'handcuffs', price = 0, amount = 50 },
        { name = 'empty_evidence_bag', price = 0, amount = 50 },
        { name = 'police_stormram', price = 0, amount = 50 },
        { name = 'armor', price = 0, amount = 50 },
        { name = 'radio', price = 0, amount = 50 },
        { name = 'heavyarmor', price = 0, amount = 50 },
    },
    ['ambulance'] = {
        { name = 'radio', price = 0, amount = 50 },
        { name = 'bandage', price = 0, amount = 50 },
        { name = 'painkillers', price = 0, amount = 50 },
        { name = 'firstaid', price = 0, amount = 50 },
        --{ name = 'weapon_flashlight',       price = 0, amount = 50, },
        --{ name = 'weapon_fireextinguisher', price = 0, amount = 50, },
    },
    ['mechanic'] = {
        { name = 'veh_toolbox', price = 0, amount = 50 },
        { name = 'veh_armor', price = 0, amount = 50 },
        { name = 'veh_brakes', price = 0, amount = 50 },
        { name = 'veh_engine', price = 0, amount = 50 },
        { name = 'veh_suspension', price = 0, amount = 50 },
        { name = 'veh_transmission', price = 0, amount = 50 },
        { name = 'veh_turbo', price = 0, amount = 50 },
        { name = 'veh_interior', price = 0, amount = 50 },
        { name = 'veh_exterior', price = 0, amount = 50 },
        { name = 'veh_wheels', price = 0, amount = 50 },
        { name = 'veh_neons', price = 0, amount = 50 },
        { name = 'veh_xenons', price = 0, amount = 50 },
        { name = 'veh_tint', price = 0, amount = 50 },
        { name = 'veh_plates', price = 0, amount = 50 },
        { name = 'nitrous', price = 0, amount = 50 },
        { name = 'tunerlaptop', price = 0, amount = 50 },
        { name = 'repairkit', price = 0, amount = 50 },
        { name = 'advancedrepairkit', price = 0, amount = 50 },
        { name = 'tirerepairkit', price = 0, amount = 50 },
    },
}

Config.Locations = {
    ['jetstop'] = {
        ['label'] = 'Jet Stop',
        ['coords'] = Vector(563550, 561761, 4570),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'convenience',
        ['blipColor'] = LinearColor(1.0, 0.85, 0.2, 1.0),
        ['description'] = 'Snacks, drinks & essentials',
        ['delivery'] = Vector(26.45, -1315.51, 29.62),
        ['useStock'] = false,
    },
    ['jetstop2'] = {
        ['label'] = 'Jet Stop',
        ['coords'] = Vector(571221, 459692, 4571),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'convenience',
        ['blipColor'] = LinearColor(1.0, 0.85, 0.2, 1.0),
        ['description'] = 'Snacks, drinks & essentials',
        ['delivery'] = Vector(-352276, -208951, -2883),
        ['useStock'] = false,
    },
    ['greenside'] = {
        ['label'] = 'GreenSide',
        ['coords'] = Vector(574053, 518499, 4562),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'grocery',
        ['blipColor'] = LinearColor(0.3, 0.8, 0.3, 1.0),
        ['description'] = 'Groceries & fresh produce',
        ['delivery'] = Vector(-265472, -102698, -1851),
        ['useStock'] = false,
    },
    ['newchapter'] = {
        ['label'] = 'New Chapter Books',
        ['coords'] = Vector(574188, 519519, 4563),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'shop',
        ['blipColor'] = LinearColor(0.4, 0.6, 1.0, 1.0),
        ['description'] = 'Books & magazines',
        ['delivery'] = Vector(574188, 519519, 4563),
        ['useStock'] = false,
    },
    ['dibsmart'] = {
        ['label'] = 'Dibs Mart',
        ['coords'] = Vector(574078, 522000, 4563),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'convenience',
        ['blipColor'] = LinearColor(1.0, 0.85, 0.2, 1.0),
        ['description'] = 'Convenience store',
        ['delivery'] = Vector(574188, 519519, 4563),
        ['useStock'] = false,
    },
    ['soupsouls'] = {
        ['label'] = 'Soup Soul',
        ['coords'] = Vector(573986, 523732, 4563),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'restaurant',
        ['blipColor'] = LinearColor(1.0, 0.5, 0.1, 1.0),
        ['description'] = 'Soups & hot food',
        ['delivery'] = Vector(574188, 519519, 4563),
        ['useStock'] = false,
    },
    ['aurum'] = {
        ['label'] = 'Aurum Jewelers',
        ['coords'] = Vector(573912, 525302, 4562),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'diamond',
        ['blipColor'] = LinearColor(0.8, 0.65, 1.0, 1.0),
        ['description'] = 'Jewelry & fine accessories',
        ['delivery'] = Vector(573912, 525302, 4562),
        ['useStock'] = false,
    },
    ['sportsdepot'] = {
        ['label'] = 'Pacifica Sports Depot',
        ['coords'] = Vector(573755, 527005, 4563),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'fitness-centre',
        ['blipColor'] = LinearColor(0.2, 0.65, 1.0, 1.0),
        ['description'] = 'Sports gear & equipment',
        ['delivery'] = Vector(573755, 527005, 4563),
        ['useStock'] = false,
    },
    ['homehub'] = {
        ['label'] = 'Home Hub',
        ['coords'] = Vector(574990, 527456, 4562),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipIcon'] = 'furniture',
        ['blipColor'] = LinearColor(0.8, 0.6, 0.3, 1.0),
        ['description'] = 'Home goods & furnishings',
        ['delivery'] = Vector(574990, 527456, 4562),
        ['useStock'] = false,
    },
    ['deadeye_arms'] = {
        ['label'] = 'Deadeye Arms',
        ['coords'] = Vector(572940, 547706, 4560),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_COP_IDLES',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Gun Shop',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipIcon'] = 'danger',
        ['blipColor'] = LinearColor(1.0, 0.2, 0.2, 1.0),
        ['description'] = 'Licensed firearms & ammunition',
        ['delivery'] = Vector(572940, 547706, 4560),
        ['useStock'] = false,
    },
    ['police'] = {
        ['label'] = 'Police Shop',
        ['coords'] = Vector(561977, 572563, 4653),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_COP_IDLES',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = Vector(-339619, -148855, -2883),
        ['requiredJob'] = 'police',
    },
    ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = Vector(0, 0, 0),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = Vector(0, 0, 0),
        ['requiredJob'] = 'ambulance',
    },
    ['mechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = Vector(567465, 562061, 4548),
        ['heading'] = 0,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Mechanic Shop',
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = Vector(-350720, -114233, -2878),
        ['requiredJob'] = 'mechanic',
    },
    ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = Vector(-261030, -240157, -2707),
        ['heading'] = -65,
        ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
        ['animation'] = 'WORLD_HUMAN_COP_IDLES',
        ['targetIcon'] = 'shopping-basket',
        ['targetLabel'] = 'Open Prison Shop',
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipIcon'] = 'prison',
        ['blipColor'] = LinearColor(0.55, 0.55, 0.55, 1.0),
        ['description'] = 'Prison canteen',
        ['delivery'] = Vector(-261030, -240157, -2707),
    },
}
