Config = {
    Locations = {
        ['palmera_medical'] = {
            label                 = 'Palmera Medical Center',
            checking              = { Vector(559879, 432795, 4545) },
            duty                  = { Vector(559348, 432941, 4545) },
            stash                 = { Vector(557885, 434102, 4545) },
            vehicle               = { Vector(564197, 441202, 4537) },
            helicopter            = { Vector(0, 0, 0) },
            vehicleSpawn          = { coords = Vector(0, 0, 0), heading = 0 },
            helicopterSpawn       = { coords = Vector(0, 0, 0), heading = 0 },
            authorizedVehicles    = {
                [0] = { ['bp_ambulance'] = 'Ambulance' }
            },
            authorizedHelicopters = {
                [0] = { ['bp_aheli'] = 'EMS Heli' }
            },
            beds                  = {
                { coords = Vector(558823, 436869, 4608), heading = 121, taken = false },
                { coords = Vector(558218, 436507, 4608), heading = 121, taken = false },
                { coords = Vector(557995, 436288, 4608), heading = 125, taken = false },
                { coords = Vector(557408, 435953, 4608), heading = 125, taken = false },
                { coords = Vector(556594, 435381, 4608), heading = 122, taken = false },
                { coords = Vector(556354, 435215, 4608), heading = 120, taken = false },
                { coords = Vector(556020, 434951, 4608), heading = 127, taken = false },
                { coords = Vector(555760, 434804, 4608), heading = 126, taken = false },
            },
        },
        ['palmera_trauma'] = {
            label                 = 'Palmera Trauma Center',
            checking              = { Vector(555776, 438849, 4545) },
            duty                  = { Vector(555388, 439094, 4545) },
            stash                 = { Vector(552647, 438625, 4545) },
            vehicle               = { Vector(560783, 446224, 4537) },
            helicopter            = { Vector(0, 0, 0) },
            vehicleSpawn          = { coords = Vector(0, 0, 0), heading = 0 },
            helicopterSpawn       = { coords = Vector(0, 0, 0), heading = 0 },
            authorizedVehicles    = {
                [0] = { ['bp_ambulance'] = 'Ambulance' }
            },
            authorizedHelicopters = {
                [0] = { ['bp_aheli'] = 'EMS Heli' }
            },
            beds                  = {
                { coords = Vector(553985, 440255, 4608), heading = 215, taken = false },
                { coords = Vector(553789, 440580, 4608), heading = 212, taken = false },
                { coords = Vector(553570, 440881, 4608), heading = 211, taken = false },
                { coords = Vector(553342, 441202, 4608), heading = 215, taken = false },
                { coords = Vector(554402, 441520, 4608), heading = 31,  taken = false },
                { coords = Vector(554191, 441828, 4608), heading = 33,  taken = false },
                { coords = Vector(553971, 442140, 4608), heading = 37,  taken = false },
            },
        },
    },

    Bones = {
        ['Root'] = 'root',
        ['Hips'] = 'pelvis',
        ['Spine'] = 'spine_01',
        ['Spine1'] = 'spine_02',
        ['Spine2'] = 'spine_03',
        ['Spine3'] = 'spine_04',
        ['Spine4'] = 'spine_05',
        ['Neck'] = 'neck_01',
        ['Neck1'] = 'neck_02',
        ['Head'] = 'head',
        ['LeftShoulder'] = 'clavicle_l',
        ['RightShoulder'] = 'clavicle_r',
        ['LeftArm'] = 'upperarm_l',
        ['RightArm'] = 'upperarm_r',
        ['LeftArmTwist'] = 'upperarm_twist_01_l',
        ['RightArmTwist'] = 'upperarm_twist_01_r',
        ['LeftForeArm'] = 'lowerarm_l',
        ['RightForeArm'] = 'lowerarm_r',
        ['LeftForeArmTwist'] = 'lowerarm_twist_01_l',
        ['RightForeArmTwist'] = 'lowerarm_twist_01_r',
        ['LeftHand'] = 'hand_l',
        ['RightHand'] = 'hand_r',
        ['LeftThigh'] = 'thigh_l',
        ['RightThigh'] = 'thigh_r',
        ['LeftThighTwist'] = 'thigh_twist_01_l',
        ['RightThighTwist'] = 'thigh_twist_01_r',
        ['LeftCalf'] = 'calf_l',
        ['RightCalf'] = 'calf_r',
        ['LeftCalfTwist'] = 'calf_twist_01_l',
        ['RightCalfTwist'] = 'calf_twist_01_r',
        ['LeftFoot'] = 'foot_l',
        ['RightFoot'] = 'foot_r',
        ['LeftToeBase'] = 'ball_l',
        ['RightToeBase'] = 'ball_r',
        ['LeftHandThumb1'] = 'thumb_01_l',
        ['RightHandThumb1'] = 'thumb_01_r',
        ['LeftHandThumb2'] = 'thumb_02_l',
        ['RightHandThumb2'] = 'thumb_02_r',
        ['LeftHandThumb3'] = 'thumb_03_l',
        ['RightHandThumb3'] = 'thumb_03_r',
        ['LeftHandIndex1'] = 'index_01_l',
        ['RightHandIndex1'] = 'index_01_r',
        ['LeftHandIndex2'] = 'index_02_l',
        ['RightHandIndex2'] = 'index_02_r',
        ['LeftHandIndex3'] = 'index_03_l',
        ['RightHandIndex3'] = 'index_03_r',
        ['LeftHandMiddle1'] = 'middle_01_l',
        ['RightHandMiddle1'] = 'middle_01_r',
        ['LeftHandMiddle2'] = 'middle_02_l',
        ['RightHandMiddle2'] = 'middle_02_r',
        ['LeftHandMiddle3'] = 'middle_03_l',
        ['RightHandMiddle3'] = 'middle_03_r',
        ['LeftHandRing1'] = 'ring_01_l',
        ['RightHandRing1'] = 'ring_01_r',
        ['LeftHandRing2'] = 'ring_02_l',
        ['RightHandRing2'] = 'ring_02_r',
        ['LeftHandRing3'] = 'ring_03_l',
        ['RightHandRing3'] = 'ring_03_r',
        ['LeftHandPinky1'] = 'pinky_01_l',
        ['RightHandPinky1'] = 'pinky_01_r',
        ['LeftHandPinky2'] = 'pinky_02_l',
        ['RightHandPinky2'] = 'pinky_02_r',
        ['LeftHandPinky3'] = 'pinky_03_l',
        ['RightHandPinky3'] = 'pinky_03_r',
        ['LeftHandThumbMetacarpal'] = 'thumb_metacarpal_l',
        ['RightHandThumbMetacarpal'] = 'thumb_metacarpal_r',
        ['LeftHandIndexMetacarpal'] = 'index_metacarpal_l',
        ['RightHandIndexMetacarpal'] = 'index_metacarpal_r',
        ['LeftHandMiddleMetacarpal'] = 'middle_metacarpal_l',
        ['RightHandMiddleMetacarpal'] = 'middle_metacarpal_r',
        ['LeftHandRingMetacarpal'] = 'ring_metacarpal_l',
        ['RightHandRingMetacarpal'] = 'ring_metacarpal_r',
        ['LeftHandPinkyMetacarpal'] = 'pinky_metacarpal_l',
        ['RightHandPinkyMetacarpal'] = 'pinky_metacarpal_r',
        ['RightHandWeapon'] = 'weapon_r',
        ['LeftHandWeapon'] = 'weapon_l',
        ['IK_hand_root'] = 'ik_hand_root',
        ['IK_hand_gun'] = 'ik_hand_gun',
        ['IK_hand_l'] = 'ik_hand_l',
        ['IK_hand_r'] = 'ik_hand_r',
        ['IK_foot_root'] = 'ik_foot_root',
        ['IK_foot_l'] = 'ik_foot_l',
        ['IK_foot_r'] = 'ik_foot_r'
    }
}
